export const listWardCommune = [
  'Bùi Thị Xuân',
  'Đống Đa',
  'Ghềnh Ráng',
  'Hải Cảng',
  'Lê Lợi',
  'Lý Thường Kiệt',
  'Nhơn Bình',
  'Nhơn Châu',
  'Nhơn Hải',
  'Nhơn Hội',
  'Nhơn Lý',
  'Nhơn Phú',
  'Ngô Mây',
  'Nguyễn Văn Cừ',
  'Phước Mỹ',
  'Quang Trung',
  'Thị Nại',
  'Trần Phú',
  'Trần Quang Diệu',
];
